---
- stat: path=/etc/php5/apache2/php.ini
  register: mod_php

- stat: path=/etc/php5/cli/php.ini
  register: phpcli

- include: mod_php.yml
  when: mod_php.stat.exists

- include: phpcli.yml
  when: phpcli.stat.exists
